spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dispatch-delivery
    username: vendease
    password: root12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
